import { Inter } from "next/font/google";
import "./globals.css";
import { NavBar } from "@/components/navegacion/NavBar";
import ToastCustom from "@/components/toast/ToastCustom";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body className={inter.className}>
        <ToastCustom />
        <NavBar />
        {children}
        </body>
    </html>
  );
}
